# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 353)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 41, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButtonGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGenerate.setGeometry(QtCore.QRect(120, 270, 131, 32))
        self.pushButtonGenerate.setObjectName("pushButtonGenerate")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 41, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(150, 30, 71, 20))
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setAutoExclusive(True)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_1.setEnabled(True)
        self.checkBox_1.setGeometry(QtCore.QRect(150, 10, 71, 20))
        self.checkBox_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_1.setChecked(True)
        self.checkBox_1.setAutoExclusive(True)
        self.checkBox_1.setTristate(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 70, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 70, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 180, 41, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(150, 120, 41, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 120, 41, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 150, 41, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(150, 150, 41, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(260, 180, 41, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(150, 180, 41, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(50, 230, 151, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(270, 230, 41, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.xLength = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xLength.setGeometry(QtCore.QRect(100, 120, 51, 22))
        self.xLength.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.xLength.setMaximum(300.0)
        self.xLength.setObjectName("xLength")
        self.xRes = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xRes.setGeometry(QtCore.QRect(210, 120, 51, 22))
        self.xRes.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.xRes.setObjectName("xRes")
        self.sensorDelay = QtWidgets.QSpinBox(self.centralwidget)
        self.sensorDelay.setGeometry(QtCore.QRect(210, 230, 42, 22))
        self.sensorDelay.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sensorDelay.setMaximum(500)
        self.sensorDelay.setObjectName("sensorDelay")
        self.rotationRes = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rotationRes.setGeometry(QtCore.QRect(210, 180, 51, 22))
        self.rotationRes.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rotationRes.setMaximum(300.0)
        self.rotationRes.setObjectName("rotationRes")
        self.zLength = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zLength.setGeometry(QtCore.QRect(100, 150, 51, 22))
        self.zLength.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.zLength.setDecimals(2)
        self.zLength.setMaximum(300.0)
        self.zLength.setObjectName("zLength")
        self.zRes = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zRes.setGeometry(QtCore.QRect(210, 150, 51, 22))
        self.zRes.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.zRes.setMaximum(300.0)
        self.zRes.setObjectName("zRes")
        self.rotationLength = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rotationLength.setGeometry(QtCore.QRect(100, 180, 51, 22))
        self.rotationLength.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rotationLength.setMaximum(300.0)
        self.rotationLength.setObjectName("rotationLength")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.menufile.addAction(self.actionsave_as)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox_1, self.checkBox_2)
        MainWindow.setTabOrder(self.checkBox_2, self.pushButtonGenerate)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "x-axis"))
        self.pushButtonGenerate.setText(_translate("MainWindow", "Generate"))
        self.label_3.setText(_translate("MainWindow", "z-axis "))
        self.checkBox_2.setText(_translate("MainWindow", "2d-scan"))
        self.checkBox_1.setText(_translate("MainWindow", "3d-scan"))
        self.label_4.setText(_translate("MainWindow", "Scan \n"
"length/area"))
        self.label_5.setText(_translate("MainWindow", "Resolution/ \n"
" increments"))
        self.label_6.setText(_translate("MainWindow", "bed"))
        self.label_7.setText(_translate("MainWindow", "[mm]"))
        self.label_8.setText(_translate("MainWindow", "[mm]"))
        self.label_9.setText(_translate("MainWindow", "[mm]"))
        self.label_10.setText(_translate("MainWindow", "[mm]"))
        self.label_11.setText(_translate("MainWindow", "[deg]"))
        self.label_12.setText(_translate("MainWindow", "[deg]"))
        self.label_13.setText(_translate("MainWindow", "measuring time sensor"))
        self.label_14.setText(_translate("MainWindow", "[ms]"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

